export const asyncTypes = Object.freeze({
    COMPLETE_TASKS_ASYNC: 'COMPLETE_TASKS_ASYNC',
    CREATE_TASK_ASYNC:    'CREATE_TASK_ASYNC',
    DELETE_TASK_ASYNC:    'DELETE_TASK_ASYNC',
    FETCH_TASKS_ASYNC:    'FETCH_TASKS_ASYNC',
    UPDATE_TASK_ASYNC:    'UPDATE_TASK_ASYNC',
});
